### ISSUE TITLE
request for more info about cab and msha

### ISSUE THREAD

**Issue by agreppin** [crea7or/cppreference2mshelp#2]
Please provide more info on how to use the cab and msha files in the repo:
- what are the cab and msha files for ?
- write a couple more lines on how to use / install them 

Thank you !

**Comment by crea7or** [comment]
These files for Microsoft Help (included in the every Microsoft Visual Studio). They can be installed in two clicks (plus ok):
![capture](https://user-images.githubusercontent.com/467357/31906411-b730a1b4-b839-11e7-8e70-992d43750201.PNG)

**Comment by agreppin** [comment]
Ok !
I now have found the missing steps to use it: [Visual Studio 2017: Getting Started with Help Viewer](https://social.technet.microsoft.com/wiki/contents/articles/37786.visual-studio-2017-getting-started-with-help-viewer.aspx)

And an extra step to have the F1 key jump directly to the cppereference doc is:
![cppreference_mshelp_msha](https://user-images.githubusercontent.com/26579013/31947670-297a2ac4-b8d5-11e7-850f-9168748132fa.png)

Thank you for this project !
