### ISSUE TITLE
What's the format digital certificate need for compile chm files.

### ISSUE THREAD

**Issue by liudonghua123** [crea7or/cppreference2mshelp#3]
I looked the documentation [Obtain a digital certificate and create a digital signature](https://support.office.com/en-us/article/obtain-a-digital-certificate-and-create-a-digital-signature-e3d9d813-3305-4164-a820-2e063d86e512), and I successfully create a digital certificate. When I want to export, I don't know what should I choose.

![image](https://user-images.githubusercontent.com/2276718/36978367-4116915c-20bf-11e8-85a3-56dd1e1c9f53.png)

**Comment by liudonghua123** [comment]
I looked the `compile_c.cmd` and find the `signtool.exe sign /a`, according to the usage of `signtool`. It does not need a digital certificate. 

Could you please make this `README.md` more easy to understand.

![image](https://user-images.githubusercontent.com/2276718/36978835-8c65bb32-20c0-11e8-9867-db21a50541a2.png)

**Comment by crea7or** [comment]
*.chm help files should not be signed. Only *.cab files should be signed.
